version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node Dependencies
          command: npm ci --cache .npm --prefer-offline --no-audit
      - save_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./.npm
      - run:
          name: Check Linting
          command: npm run lint:ci
      - run:
          name: Check Formatting
          command: npm run format:check
      - run:
          name: Build Typescript Project
          command: npm run build
      - run:
          name: Running Unit Tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - persist_to_workspace:
          root: .
          paths:
            - dist
  docker_build_push:
    docker:
      - image: cimg/base:2021.11
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: docker build -t ghcr.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
      - run: echo $GITHUB_TOKEN | docker login ghcr.io -u $CIRCLE_PROJECT_USERNAME --password-stdin
      - run: docker push ghcr.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

workflows:
  build-test-push:
    jobs:
      - build_test
      - docker_build_push:
          requires:
            - build_test
